# @package _group_
num_samples: 100

grace_period: 30

num_cpus: 4
num_gpus: 0.333


hyperparameters:
  - key: loss.0.kwargs.tau
    type: uniform
    values: [0.001, 3]

  - key: loss.0.kwargs.mu
    type: uniform
    values: [0.01, 0.1]
