# @package _group_
num_samples: 6

grace_period: 10

num_cpus: 16
num_gpus: 1


hyperparameters:
  - key: loss.0.kwargs.neg_margin
    type: uniform
    values: [0.2, 0.7]

  - key: loss.0.kwargs.pos_margin
    type: uniform
    values: [0.7, 1.0]
