# @package _group_
num_samples: 100

grace_period: 50

num_cpus: 4
num_gpus: 0.333


hyperparameters:
  - key: loss.1.weight
    type: uniform
    values: [0.001, 2]

  - key: loss.1.kwargs.neg_margin
    type: uniform
    values: [0.5, 0.7]

  - key: loss.1.kwargs.pos_margin
    type: uniform
    values: [0.9, 1.0]
