# @package _group_
- name: SupAP
  weight: 1.0
  kwargs:
    temp: 0.01
    tau: 100.0
    offset: 1.0
    margin: 0.05
    start: 0.0

- name: CalibrationLoss
  weight: 1.0
  kwargs:
    pos_margin: 0.9
    neg_margin: 0.6
