# @package _group_
experiment_name: ???
log_dir: "${env:HOME}/experiments/neurips"
seed: ???
resume: null

warm_up: -1
warm_up_key: fc

max_iter: 50

train_eval_freq: -1
val_eval_freq: -1
test_eval_freq: 5
eval_bs: 96
save_model: 5
eval_split: test
principal_metric: recall_at_1_level0

num_workers: 16
pin_memory: True

apex: False
parallel_crit: False
