defaults:

    - experience: default

    - grid_search: default

    - dataset: sop

    - loss: roadmap

    - memory: default

    - model: resnet

    - optimizer: sop

    - transform: sop

hydra:
  run:
    dir: ${experience.log_dir}/${experience.experiment_name}/outputs
