# @package _group_
optimizer:
  Adam:
    backbone:
      lr: 0.00001
      weight_decay: 0.0004
    fc:
      lr: 0.00001
      weight_decay: 0.0004

scheduler:
  MultiStepLR:
    milestones: [30, 70]
    gamma: 0.3
    last_epoch: -1
