# @package _group_
optimizer:
  Adam:
    backbone:
      lr: 0.00001
      weight_decay: 0.0001
    fc:
      lr: 0.00001
      weight_decay: 0.0001

scheduler:
  MultiStepLR:
    milestones: [25]
    gamma: 0.1
    last_epoch: -1
