# @package _group_
name: INaturalistDataset
kwargs:
  data_dir: /local/DEEPLEARNING/image_retrieval/Inaturalist

sampler:
  name: MPerClassSampler
  kwargs:
    batch_size: 128
    samples_per_class: 4
