# @package _group_
name: InShopDataset
kwargs:
  data_dir: /local/DEEPLEARNING/image_retrieval/inshop
  hierarchy_mode: 'all'

sampler:
  name: MPerClassSampler
  kwargs:
    batch_size: 128
    samples_per_class: 4
