# @package _group_
- name: MarginAP
  weight: 1.0
  kwargs:
    temp: 0.01
    tau: 100.0
    offset: 1.44
    margin: 0.05

- name: ContrastiveLoss
  weight: 1.0
  kwargs:
    pos_margin: 0.9
    neg_margin: 0.6
