# @package _group_
- name:  ScheduledSlopeAP
  weight: 1.0
  kwargs:
    mu_n_range:
      10: 0.01
      30: 0.05
      55: 0.1
    mu_p_range:
      15: 0.1
      50: 0.05
    num_steps: 50
    scheduled_type: step
