# @package _group_
- name: Adam
  params: backbone
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
  scheduler_on_step:
  scheduler_on_val:
    name: ReduceLROnPlateau
    key: recall_at_1_level0
    kwargs:
      mode: max
      factor: 0.3
      patience: 5
      cooldown: 2

- name: Adam
  params: fc
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
  scheduler_on_step:
  scheduler_on_val:
    name: ReduceLROnPlateau
    key: recall_at_1_level0
    kwargs:
      mode: max
      factor: 0.3
      patience: 5
      cooldown: 2
