# @package _group_
- name: RMSprop
  params: backbone
  kwargs:
    lr: 0.000001
    weight_decay: 0.0001
    momentum: 0.9
  scheduler_on_epoch:
  scheduler_on_step:
  scheduler_on_val:
    name: ReduceLROnPlateau
    key: recall_at_1_level0
    kwargs:
      mode: max
      factor: 0.1
      patience: 4
      cooldown: 0

- name: RMSprop
  params: fc
  kwargs:
    lr: 0.000001
    weight_decay: 0.0001
    momentum: 0.9
  scheduler_on_epoch:
  scheduler_on_step:
  scheduler_on_val:
    name: ReduceLROnPlateau
    key: recall_at_1_level0
    kwargs:
      mode: max
      factor: 0.1
      patience: 4
      cooldown: 0
