# @package _group_
- name: AdamW
  params:
  kwargs:
    lr: 0.000005
    weight_decay: 0.0005
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [25]
      gamma: 0.1
      last_epoch: -1
  scheduler_on_step:
  scheduler_on_val:
