# @package _group_
- name: Adam
  params: backbone
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [30,70]
      gamma: 0.3
  scheduler_on_step:
  scheduler_on_val:

- name: Adam
  params: fc
  kwargs:
    lr: 0.00002
    weight_decay: 0.0001
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [30,70]
      gamma: 0.3
  scheduler_on_step:
  scheduler_on_val:
