# @package _group_
- name: AdamW
  params: backbone
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [25]
      gamma: 0.1
      last_epoch: -1
  scheduler_on_step:
  scheduler_on_val:

- name: AdamW
  params: fc
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [25]
      gamma: 0.1
      last_epoch: -1
  scheduler_on_step:
  scheduler_on_val:
