defaults:

    - experience: cnam

    - dataset: sop

    - general: sop

    - loss: smoothap

    - memory: default

    - model: resnet

    - optimizer: sop

    - transform: sop

# hydra:
#   run:
#     dir: ${experience.log_dir}/${experience.experiment_name}/outputs
