# @package _group_
- name: Adam
  params: backbone
  kwargs:
    lr: 0.00001
    weight_decay: 0.0001
  scheduler_on_epoch:
    name: MultiStepLR
    kwargs:
      milestones: [100]
      gamma: 0.1
      last_epoch: -1
  scheduler_on_step:
  scheduler_on_val:
